package org.example.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Hockey was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Hockey extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String NUMBER_PROPERTY = "number";
    public static final String POSITION_PROPERTY = "position";
    public static final String TEAM_PROPERTY = "team";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNumber(Integer number) {
        writeProperty("number", number);
    }
    public Integer getNumber() {
        return (Integer)readProperty("number");
    }

    public void setPosition(String position) {
        writeProperty("position", position);
    }
    public String getPosition() {
        return (String)readProperty("position");
    }

    public void setTeam(String team) {
        writeProperty("team", team);
    }
    public String getTeam() {
        return (String)readProperty("team");
    }

}
