FROM docker.io/centos:7


ARG NUODB_BAMBOO_RPM

RUN yum -y install --setopt=tsflags=nodocs openssh-server java-1.8.0-openjdk net-tools which emacs dstat htop strace gdb iotop python vim && yum clean all
#RUN curl -SL $NUODB_BAMBOO_RPM -o /tmp/nuodb.rpm \

ADD scripts /scripts
COPY show /usr/bin/

RUN chmod -R +x /scripts/

ENV PATH=/opt/nuodb/bin:${PATH}

ENTRYPOINT /scripts/entrypoint-ycsb.sh