#!/bin/bash

if [ -z "$1" ]; then
    echo "Database Name is required"
    echo "usage: get_processes <db-name>"
    exit 1
fi

/opt/nuodb/bin/nuocmd --api-server ${PEER_ADDRESS}:8888 get processes --db-name $1