#!/bin/bash

if [ -z "$1" ]; then
    echo "Database Name is required"
    echo "usage: get_storage_groups <db-name>"
    exit 1
fi

/opt/nuodb/bin/nuocmd --api-server ${PEER_ADDRESS}:8888 get storage-groups --db-name $1