#!/bin/bash

db=$1
usr=$2
pwd=$3

if [ "$db" = "" ]; then
   echo "Usage: createHockeySchema_part dbname [user] [passwd]"
   exit 1
fi
if [ "$2" = "" ]; then usr="dba"; fi
if [ "$3" = "" ]; then pwd="goalie"; fi


## CREATE THE SCHEMA AND LOAD HOCKEY DATA

echo "create hockey tables and db partition for scoring table"
nuosql $db@nuoadmin1 --user $usr --password $pwd --schema hockey < /opt/nuodb/hockeyDemo/create-db_part.sql >& /dev/null

## Load additional data

echo "load hockey players table"
nuosql $db@nuoadmin1 --user $usr --password $pwd --schema hockey < /opt/nuodb/samples/quickstart/sql/Players.sql >& /dev/null

echo "load hockey teams table"
nuosql $db@nuoadmin1 --user $usr --password $pwd --schema hockey < /opt/nuodb/samples/quickstart/sql/Teams.sql >& /dev/null

echo "load hockey scoring table"
nuosql $db@nuoadmin1 --user $usr --password $pwd --schema hockey < /opt/nuodb/samples/quickstart/sql/Scoring.sql  >& /dev/null



