#!/bin/bash

if [ "$1" = "" ]; then
   echo "usage: createHockeySchema PEER_ADDRESS DBName DBuser DBpassword"
   exit 1
fi

AGENT=$1
DBNAME=$2
DBUSER=$3
DBPASS=$4



echo ""
echo "Creating Hockey schema, please wait..."
/opt/nuodb/bin/nuosql $DBNAME@$AGENT --schema hockey --user $DBUSER --password $DBPASS < /opt/nuodb/samples/quickstart/sql/create-db.sql &> /dev/null

echo "loading player data..."
/opt/nuodb/bin/nuosql $DBNAME@$AGENT --schema hockey --user $DBUSER --password $DBPASS < /opt/nuodb/samples/quickstart/sql/Players.sql   &> /dev/null

echo "loading scoring data..."
/opt/nuodb/bin/nuosql $DBNAME@$AGENT --schema hockey --user $DBUSER --password $DBPASS < /opt/nuodb/samples/quickstart/sql/Scoring.sql   &> /dev/null

echo "loading team data..."
/opt/nuodb/bin/nuosql $DBNAME@$AGENT --schema hockey --user $DBUSER --password $DBPASS < /opt/nuodb/samples/quickstart/sql/Teams.sql  &> /dev/null

echo "Done"
